import com.media.eximio.auth.*
import com.media.eximio.*

class BootStrap {

    def init = { servletContext ->
//        def role = new Authority(authority: 'ROLE_ADMIN').save()
//        def role1 = new Authority(authority: 'ROLE_HOSPITAL').save()
//        def role2 = new Authority(authority: 'ROLE_ORGANIZATION').save()
//        def user1 = new User(username:'lindadmin@lind.com'.trim(),password:'123456'.trim(),fullname:'LIND Administrator'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user1 = new User(username:'harapankita@lind.com'.trim(),password:'123456'.trim(),fullname:'RSAB Harapan Kita Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user2 = new User(username:'advent@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Advent Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user3 = new User(username:'borromeus@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Borromeus Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user4 = new User(username:'brawijaya@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Brawijaya  Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user5 = new User(username:'kencana@lind.com'.trim(),password:'123456'.trim(),fullname:'RSCM Kencana Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user6 = new User(username:'oensolo@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Dr. Oen Solo Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user7 = new User(username:'gotongroyong@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Gotong Royong Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user8 = new User(username:'husadautama@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Husada Utama Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user9 = new User(username:'hermina@lind.com'.trim(),password:'123456'.trim(),fullname:'RSIA Hermina Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user10 = new User(username:'meilia@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Meilia Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user11 = new User(username:'melinda@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Melinda Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user12 = new User(username:'melindabandung@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Melinda Bandung Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user13 = new User(username:'moewardi@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Moewardi Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user14 = new User(username:'pik@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Pantai Indah Kapuk Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user15 = new User(username:'pluit@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Pluit Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user16 = new User(username:'rspi@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Pondok Indah Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user17 = new User(username:'premiere@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Premiere Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user18 = new User(username:'puricinere@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Puri Cinere Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user19 = new User(username:'royaltaruma@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Royal Taruma Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user20 = new User(username:'santosa@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Santosa Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user21 = new User(username:'siloamkj@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Siloam Kebon Jeruk Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user22 = new User(username:'charitas@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Charitas Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user23 = new User(username:'dharmais@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Dharmais Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user24 = new User(username:'mitrasetia@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Mitra Setia Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user25 = new User(username:'mitrakeluarga@lind.com'.trim(),password:'123456'.trim(),fullname:'RS Mitra Keluarga Kelapa Gading Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        
//        def user26 = new User(username:'idibandung@lind.com'.trim(),password:'123456'.trim(),fullname:'IDI Bandung Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user27 = new User(username:'pogipusat@lind.com'.trim(),password:'123456'.trim(),fullname:'POGI Pusat Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user28 = new User(username:'perki@lind.com'.trim(),password:'123456'.trim(),fullname:'PERKI Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user29 = new User(username:'papdi@lind.com'.trim(),password:'123456'.trim(),fullname:'PB PAPDI Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user30 = new User(username:'idaipusat@lind.com'.trim(),password:'123456'.trim(),fullname:'IDAI Pusat Admin'.trim(),specialist:'-'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
        
//        def user2 = new User(username:'fita_m@gmail.com'.trim(),password:'123456'.trim(),fullname:'dr. Fita Moeslichan, SpA'.trim(),specialist:' Anak'.trim(),city:'Bandung'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user3 = new User(username:'frieda@gmail.com'.trim(),password:'123456'.trim(),fullname:'dr. Frieda Hartono, SpA'.trim(),specialist:' Anak'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user4 = new User(username:'gatami@gmail.com'.trim(),password:'123456'.trim(),fullname:'dr. Gatami, SpA'.trim(),specialist:' Anak'.trim(),city:	'Jakarta'.trim(),country:'Indonesia'.trim(),createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user5 = new User(username:'hari_m@gmail.com'.trim(),password:'123456'.trim(),fullname:'dr. Hari Martono, SpA'.trim(),specialist:' Anak'.trim(),city:'Solo'.trim(),country:'Indonesia'.trim(),createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user6 = new User(username:'irma_r@gmail.com'.trim(),password:'123456'.trim(),fullname:'Dr. Irma Rochima Puspita, SpA'.trim(),specialist:' Anak'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user7 = new User(username:'johann@gmail.com'.trim(),password:'123456'.trim(),fullname:'dr. Johannus Edwin, SpA'.trim(),specialist:' Anak'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user8 = new User(username:'johnny@gmail.com'.trim(),password:'123456'.trim(),fullname:'dr. Johnny Nurman, SpA'.trim(),specialist:' Anak'.trim(),city:'Jakarta'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user9 = new User(username:'laksmi@gmail.com'.trim(),password:'123456'.trim(),fullname:'dr. Laksmi Suci Handini, SpA'.trim(),specialist:' Anak'.trim(),city:'Surabaya'.trim(),country:'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user10 = new User(username:'tini_a@gmail.com'.trim(),password:'123456'.trim(),fullname:'dr. Tini A. Hanapie. SpA'.trim(),specialist:' Anak'.trim(),city:'Solo'	,country:'Indonesia'.trim(),createdate:	new Date()	,updatedate:	new Date()	).save() 
//        def user11 = new User(username:	'didi_d@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Didi Dewantoro, SpOG'	,specialist:	' Anak'	,city:	'Surabaya'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user12 = new User(username:	'andry,@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Andry, SpOG'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user13 = new User(username:	'nana_a@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Nana Agustina, SpOG'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user14 = new User(username:	'm_luc@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. M. Lucky Satria, SpOG'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user15 = new User(username:	'nova_h@gmail.com'.trim(),password:'123456'.trim(),fullname:	'Dr. Nova Hanafi, SpOG'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user16 = new User(username:	'aldika@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Aldika akbar, SpOG'	,specialist:	' Anak'	,city:	'Bandung'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user17 = new User(username:	'uf_bag@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. UF Bagazi, SpOG'	,specialist:	' Anak'	,city:	'Bandung'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user18 = new User(username:	'med_d@gmail.com'.trim(),password:'123456'.trim(),fullname:	'DR. MED. Dr. Calvin Tjong, SpOG'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user19 = new User(username:	'kartik@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Kartika Hapsari, SpOG'	,specialist:	' Anak'	,city:	'Solo'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user20 = new User(username:	'diana_@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Diana Mauria Ratna Asih, SpOG'	,specialist:	' Anak'	,city:	'Bogor'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user21 = new User(username:	'titos_@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Titos Ahimsa, SpPD'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user22 = new User(username:	'murdan@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Murdani Abdulah, SpPD'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user23 = new User(username:	'marcel@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Marcelius, SpPD'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user24 = new User(username:	'prasna@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Prasna Pramita, SpPD'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user25 = new User(username:	'chaidi@gmail.com'.trim(),password:'123456'.trim(),fullname:	'Dr. Chaidir Aulia, SpPD, KGEH'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user26 = new User(username:	'luki_a@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Luki Agustina, SpPD'	,specialist:	' Anak'	,city:	'Bandung'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user27 = new User(username:	'femmy_@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Femmy Nurul Akbar, SpPD'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user28 = new User(username:	'wisman@gmail.com'.trim(),password:'123456'.trim(),fullname:	'DR. Wismandari, SpPD'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user29 = new User(username:	'alvin_@gmail.com'.trim(),password:'123456'.trim(),fullname:	'dr. Alvin Tagor Harahap, SpPD'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user30 = new User(username:	'leo_w@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Leo W.Natasuria, SpPD'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user31 = new User(username:	'jordan@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Jordan Bakhriansyah, SpJP'	,specialist:	' Anak'	,city:	'Surabaya'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user32 = new User(username:	'beny_h@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Beny Hartono, SpJP, FIHA'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user33 = new User(username:	'agus_r@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Agus Riawan, SpJP'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user34 = new User(username:	'd_abd@gmail.com'.trim(),password:'123456'	,fullname:	'dr. D. Abdullah Saleh, SpJP'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user35 = new User(username:	'djoko_@gmail.com'.trim(),password:'123456'	,fullname:	'Dr. Djoko Maryono SpJP, FIHA, FACC'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user36 = new User(username:	'santos@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Santoso Sapardan, SpJP'	,specialist:	' Anak'	,city:	'Bandung'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user37 = new User(username:	'sunary@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Sunarya Soerianata, SpJP'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user38 = new User(username:	'taufik@gmail.com'.trim(),password:'123456'	,fullname:	'DR. Taufik A Pohan, SpJP'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user39 = new User(username:	'david_@gmail.com'.trim(),password:'123456'	,fullname:	'dr. David Lucman, SpJP'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user40 = new User(username:	'winart@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Winarto, SpJP, FIHA'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user41 = new User(username:	'homas_@gmail.com'.trim(),password:'123456'	,fullname:	'dr.Thomas Aquino da Gomez'	,specialist:	' Anak'	,city:	'Palembang'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user42 = new User(username:	'dwi_pu@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Dwi Putra'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user43 = new User(username:	'vonty_@gmail.com'.trim(),password:'123456'	,fullname:	'dr. Vonty Elfrida Sihaloho'	,specialist:	' Anak'	,city:	'Surabaya'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user44 = new User(username:	'ndah_f@gmail.com'.trim(),password:	'123456'	,fullname:	'dr.Indah Fadli B.Med, Sc'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user45 = new User(username:	'dimas_@gmail.com'.trim(),password:	'123456'	,fullname:	'Dr. Dimas Rama Hermawan'	,specialist:	' Anak'	,city:	'Bandung'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user46 = new User(username:	'ganjar@gmail.com'.trim(),password:	'123456'	,fullname:	'dr. Ganjar Eri Satria'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user47 = new User(username:	'iqbal_@gmail.com'.trim(),password:	'123456'	,fullname:	'dr. Iqbal Maulana'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user48 = new User(username:	'dianty@gmail.com'.trim(),password:	'123456'	,fullname:	'DR. Dianty Puji Rahayu'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user49 = new User(username:	'eleono@gmail.com'.trim(),password:	'123456'	,fullname:	'dr. Eleonora Mitaning Christy'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//        def user50 = new User(username:	'jody_s@gmail.com'.trim(),password:	'123456'	,fullname:	'dr. Jody Setyadi'	,specialist:	' Anak'	,city:	'Jakarta'	,country:	'Indonesia'	,createdate:	new Date()	,updatedate:	new Date()	).save()
//
//        UserAuthority.create(user1	,role1	)
//        UserAuthority.create(user2	,role1	)
//        UserAuthority.create(user3	,role1	)
//        UserAuthority.create(user4	,role1	)
//        UserAuthority.create(user5	,role1	)
//        UserAuthority.create(user6	,role1	)
//        UserAuthority.create(user7	,role1	)
//        UserAuthority.create(user8	,role1	)
//        UserAuthority.create(user9	,role1	)
//        UserAuthority.create(user10	,role1	)
//        UserAuthority.create(user11	,role1	)
//        UserAuthority.create(user12	,role1	)
//        UserAuthority.create(user13	,role1	)
//        UserAuthority.create(user14	,role1	)
//        UserAuthority.create(user15	,role1	)
//        UserAuthority.create(user16	,role1	)
//        UserAuthority.create(user17	,role1	)
//        UserAuthority.create(user18	,role1	)
//        UserAuthority.create(user19	,role1	)
//        UserAuthority.create(user20	,role1	)
//        UserAuthority.create(user21	,role1	)
//        UserAuthority.create(user22	,role1	)
//        UserAuthority.create(user23	,role1	)
//        UserAuthority.create(user24	,role1	)
//        UserAuthority.create(user25	,role1	)
//        UserAuthority.create(user26	,role2	)
//        UserAuthority.create(user27	,role2	)
//        UserAuthority.create(user28	,role2	)
//        UserAuthority.create(user29	,role2	)
//        UserAuthority.create(user30	,role2	)
//        UserAuthority.create(user31	,role	)
//        UserAuthority.create(user32	,role	)
//        UserAuthority.create(user33	,role	)
//        UserAuthority.create(user34	,role	)
//        UserAuthority.create(user35	,role	)
//        UserAuthority.create(user36	,role	)
//        UserAuthority.create(user37	,role	)
//        UserAuthority.create(user38	,role	)
//        UserAuthority.create(user39	,role	)
//        UserAuthority.create(user40	,role	)
//        UserAuthority.create(user41	,role	)
//        UserAuthority.create(user42	,role	)
//        UserAuthority.create(user43	,role	)
//        UserAuthority.create(user44	,role	)
//        UserAuthority.create(user45	,role	)
//        UserAuthority.create(user46	,role	)
//        UserAuthority.create(user47	,role	)
//        UserAuthority.create(user48	,role	)
//        UserAuthority.create(user49	,role	)
//        UserAuthority.create(user50	,role	)
//        
//        new Specialist(	title:	'Dr.'.trim(),	description:	'Dokter Umum '.trim(),	).save()
//        new Specialist(	title:	'Sp.A'.trim(),	description:	' Anak '.trim(),	).save()
//        new Specialist(	title:	'Sp.And'.trim(),	description:	' Andrologi '.trim(),	).save()
//        new Specialist(	title:	'Sp.An'.trim(),	description:	' Anestesiologi dan Reanimasi '.trim(),	).save()
//        new Specialist(	title:	'Sp.B'.trim(),	description:	' Bedah '.trim(),	).save()
//        new Specialist(	title:	'Sp.BA'.trim(),	description:	' Bedah Anak '.trim(),	).save()
//        new Specialist(	title:	'Sp.BM'.trim(),	description:	' Bedah Mulut dan Maksilofasial '.trim(),	).save()
//        new Specialist(	title:	'Sp.OT'.trim(),	description:	' Bedah Orthopaedi dan Traumatologi '.trim(),	).save()
//        new Specialist(	title:	'Sp.BP'.trim(),	description:	' Bedah Plastik '.trim(),	).save()
//        new Specialist(	title:	'Sp.BTKV'.trim(),	description:	' Bedah Toraks Kardiovaskuler '.trim(),	).save()
//        new Specialist(	title:	'Sp.BS'.trim(),	description:	' BedahSaraf '.trim(),	).save()
//        new Specialist(	title:	'Sp.FK'.trim(),	description:	' Farmakologi Klinik '.trim(),	).save()
//        new Specialist(	title:	'Sp.Ger'.trim(),	description:	' Geriatri '.trim(),	).save()
//        new Specialist(	title:	'Sp.JP'.trim(),	description:	' Jantung dan Pembuluh Darah '.trim(),	).save()
//        new Specialist(	title:	'Sp.EM'.trim(),	description:	' Kedaruratan Medik '.trim(),	).save()
//        new Specialist(	title:	'Sp.KFR'.trim(),	description:	' Kedokteran Fisik dan Rehabilitasi '.trim(),	).save()
//        new Specialist(	title:	'Sp.F'.trim(),	description:	' Kedokteran Forensik '.trim(),	).save()
//        new Specialist(	title:	'Sp.KGA'.trim(),	description:	' Kedokteran Gigi Anak (dokter gigi) '.trim(),	).save()
//        new Specialist(	title:	'Sp.KJ'.trim(),	description:	' Kedokteran Jiwa atau Psikiatri '.trim(),	).save()
//        new Specialist(	title:	'Sp.KN'.trim(),	description:	' Kedokteran Nuklir '.trim(),	).save()
//        new Specialist(	title:	'Sp.Ok'.trim(),	description:	' Kedokteran Okupasi (kerja) '.trim(),	).save()
//        new Specialist(	title:	'Sp.KO'.trim(),	description:	' Kedokteran Olahraga '.trim(),	).save()
//        new Specialist(	title:	'Sp.KG'.trim(),	description:	' Konservasi Gigi (dokter gigi) '.trim(),	).save()
//        new Specialist(	title:	'Sp.M'.trim(),	description:	' Mata '.trim(),	).save()
//        new Specialist(	title:	'Sp.MK'.trim(),	description:	' Mikrobiologi Klinik '.trim(),	).save()
//        new Specialist(	title:	'Sp.OG'.trim(),	description:	' Obstetri & Ginekologi (kebidanan dan kandungan) '.trim(),	).save()
//        new Specialist(	title:	'Sp.Onk.Rad '.trim(),	description:	' Onkologi Radiasi '.trim(),	).save()
//        new Specialist(	title:	'Sp.Ort'.trim(),	description:	' Ortodonsia (perawatan maloklusi) (dokter gigi) '.trim(),	).save()
//        new Specialist(	title:	'Sp.P'.trim(),	description:	' Paru (Pulmonologi) '.trim(),	).save()
//        new Specialist(	title:	'Sp.PA'.trim(),	description:	' Patologi Anatomi '.trim(),	).save()
//        new Specialist(	title:	'Sp.PK'.trim(),	description:	' Patologi Klinik '.trim(),	).save()
//        new Specialist(	title:	'Sp.PD '.trim(),	description:	' Penyakit Dalam '.trim(),	).save()
//        new Specialist(	title:	'Sp.KK'.trim(),	description:	' Penyakit Kulit dan Kelamin '.trim(),	).save()
//        new Specialist(	title:	'Sp.PM'.trim(),	description:	' Penyakit Mulut (dokter gigi) '.trim(),	).save()
//        new Specialist(	title:	'Sp.Perio'.trim(),	description:	' Periodonsia (jaringan gusi dan penyangga gigi) '.trim(),	).save()
//        new Specialist(	title:	'Sp.Pros'.trim(),	description:	' Prostodonsia (restorasi rongga mulut) (dokter gigi) '.trim(),	).save()
//        new Specialist(	title:	'Sp.Rad'.trim(),	description:	' Radiologi '.trim(),	).save()
//        new Specialist(	title:	'Sp.RKG'.trim(),	description:	' Radiologi Kedokteran Gigi (dokter gigi) '.trim(),	).save()
//        new Specialist(	title:	'Sp.RM'.trim(),	description:	' Rehabilitasi Medik '.trim(),	).save()
//        new Specialist(	title:	'Sp.S'.trim(),	description:	' Saraf '.trim(),	).save()
//        new Specialist(	title:	'Sp.THT'.trim(),	description:	' Telinga Hidung Tenggorok '.trim(),	).save()
//        new Specialist(	title:	'Sp.U'.trim(),	description:	' Urologi '.trim(),	).save()
//        
//        new Cities(	citiname:	'Aceh Barat '	).save()
//        new Cities(	citiname:	'Aceh Barat Daya '	).save()
//        new Cities(	citiname:	'Aceh Besar '	).save()
//        new Cities(	citiname:	'Aceh Jaya '	).save()
//        new Cities(	citiname:	'Aceh Selatan '	).save()
//        new Cities(	citiname:	'Aceh Singkil '	).save()
//        new Cities(	citiname:	'Aceh Tamiang '	).save()
//        new Cities(	citiname:	'Aceh Tengah '	).save()
//        new Cities(	citiname:	'Aceh Tenggara '	).save()
//        new Cities(	citiname:	'Aceh Timur '	).save()
//        new Cities(	citiname:	'Aceh Utara '	).save()
//        new Cities(	citiname:	'Kepulauan Seribu '	).save()
//        new Cities(	citiname:	'Agam '	).save()
//        new Cities(	citiname:	'Alor '	).save()
//        new Cities(	citiname:	'Asahan '	).save()
//        new Cities(	citiname:	'Asmat '	).save()
//        new Cities(	citiname:	'Badung '	).save()
//        new Cities(	citiname:	'Balangan '	).save()
//        new Cities(	citiname:	'Bandung '	).save()
//        new Cities(	citiname:	'Banggai '	).save()
//        new Cities(	citiname:	'Banggai Kepulauan '	).save()
//        new Cities(	citiname:	'Bangka '	).save()
//        new Cities(	citiname:	'Bangka Barat '	).save()
//        new Cities(	citiname:	'Bangka Selatan '	).save()
//        new Cities(	citiname:	'Bangka Tengah '	).save()
//        new Cities(	citiname:	'Bangkalan '	).save()
//        new Cities(	citiname:	'Bangli '	).save()
//        new Cities(	citiname:	'Banjar '	).save()
//        new Cities(	citiname:	'Banjarnegara '	).save()
//        new Cities(	citiname:	'Bantaeng '	).save()
//        new Cities(	citiname:	'Bantul '	).save()
//        new Cities(	citiname:	'Banyuasin '	).save()
//        new Cities(	citiname:	'Banyumas '	).save()
//        new Cities(	citiname:	'Banyuwangi '	).save()
//        new Cities(	citiname:	'Barito Kuala '	).save()
//        new Cities(	citiname:	'Barito Selatan '	).save()
//        new Cities(	citiname:	'Barito Timur '	).save()
//        new Cities(	citiname:	'Barito Utara '	).save()
//        new Cities(	citiname:	'Barru '	).save()
//        new Cities(	citiname:	'Batang '	).save()
//        new Cities(	citiname:	'Batanghari '	).save()
//        new Cities(	citiname:	'Batubara '	).save()
//        new Cities(	citiname:	'Bekasi '	).save()
//        new Cities(	citiname:	'Belitung '	).save()
//        new Cities(	citiname:	'Belitung Timur '	).save()
//        new Cities(	citiname:	'Belu '	).save()
//        new Cities(	citiname:	'Bener Meriah '	).save()
//        new Cities(	citiname:	'Bengkalis '	).save()
//        new Cities(	citiname:	'Bengkayang '	).save()
//        new Cities(	citiname:	'Bengkulu Selatan '	).save()
//        new Cities(	citiname:	'Bengkulu Tengah '	).save()
//        new Cities(	citiname:	'Bengkulu Utara '	).save()
//        new Cities(	citiname:	'Berau '	).save()
//        new Cities(	citiname:	'Biak Numfor '	).save()
//        new Cities(	citiname:	'Bima '	).save()
//        new Cities(	citiname:	'Bintan '	).save()
//        new Cities(	citiname:	'Bireuen '	).save()
//        new Cities(	citiname:	'Blitar '	).save()
//        new Cities(	citiname:	'Blora '	).save()
//        new Cities(	citiname:	'Boalemo '	).save()
//        new Cities(	citiname:	'Bogor '	).save()
//        new Cities(	citiname:	'Bojonegoro '	).save()
//        new Cities(	citiname:	'Bolaang Mongondow '	).save()
//        new Cities(	citiname:	'Bolaang Mongondow Selatan '	).save()
//        new Cities(	citiname:	'Bolaang Mongondow Timur '	).save()
//        new Cities(	citiname:	'Bolaang Mongondow Utara '	).save()
//        new Cities(	citiname:	'Bombana '	).save()
//        new Cities(	citiname:	'Bondowoso '	).save()
//        new Cities(	citiname:	'Bone '	).save()
//        new Cities(	citiname:	'Bone Bolango '	).save()
//        new Cities(	citiname:	'Boven Digoel '	).save()
//        new Cities(	citiname:	'Boyolali '	).save()
//        new Cities(	citiname:	'Brebes '	).save()
//        new Cities(	citiname:	'Buleleng '	).save()
//        new Cities(	citiname:	'Bulukumba '	).save()
//        new Cities(	citiname:	'Bulungan '	).save()
//        new Cities(	citiname:	'Bungo '	).save()
//        new Cities(	citiname:	'Buol '	).save()
//        new Cities(	citiname:	'Buru '	).save()
//        new Cities(	citiname:	'Buru Selatan '	).save()
//        new Cities(	citiname:	'Buton '	).save()
//        new Cities(	citiname:	'Buton Utara '	).save()
//        new Cities(	citiname:	'Ciamis '	).save()
//        new Cities(	citiname:	'Cianjur '	).save()
//        new Cities(	citiname:	'Cilacap '	).save()
//        new Cities(	citiname:	'Cirebon '	).save()
//        new Cities(	citiname:	'Dairi '	).save()
//        new Cities(	citiname:	'Deiyai '	).save()
//        new Cities(	citiname:	'Deli Serdang '	).save()
//        new Cities(	citiname:	'Demak '	).save()
//        new Cities(	citiname:	'Dharmasraya '	).save()
//        new Cities(	citiname:	'Dogiyai '	).save()
//        new Cities(	citiname:	'Dompu '	).save()
//        new Cities(	citiname:	'Donggala '	).save()
//        new Cities(	citiname:	'Empat Lawang '	).save()
//        new Cities(	citiname:	'Ende '	).save()
//        new Cities(	citiname:	'Enrekang '	).save()
//        new Cities(	citiname:	'Fakfak '	).save()
//        new Cities(	citiname:	'Flores Timur '	).save()
//        new Cities(	citiname:	'Garut '	).save()
//        new Cities(	citiname:	'Gayo Lues '	).save()
//        new Cities(	citiname:	'Gianyar '	).save()
//        new Cities(	citiname:	'Gorontalo '	).save()
//        new Cities(	citiname:	'Gorontalo Utara '	).save()
//        new Cities(	citiname:	'Gowa '	).save()
//        new Cities(	citiname:	'Gresik '	).save()
//        new Cities(	citiname:	'Grobogan '	).save()
//        new Cities(	citiname:	'Gunung Kidul '	).save()
//        new Cities(	citiname:	'Gunung Mas '	).save()
//        new Cities(	citiname:	'Halmahera Barat '	).save()
//        new Cities(	citiname:	'Halmahera Selatan '	).save()
//        new Cities(	citiname:	'Halmahera Tengah '	).save()
//        new Cities(	citiname:	'Halmahera Timur '	).save()
//        new Cities(	citiname:	'Halmahera Utara '	).save()
//        new Cities(	citiname:	'Hulu Sungai Selatan '	).save()
//        new Cities(	citiname:	'Hulu Sungai Tengah '	).save()
//        new Cities(	citiname:	'Hulu Sungai Utara '	).save()
//        new Cities(	citiname:	'Humbang Hasundutan '	).save()
//        new Cities(	citiname:	'Indragiri Hilir '	).save()
//        new Cities(	citiname:	'Indragiri Hulu '	).save()
//        new Cities(	citiname:	'Indramayu '	).save()
//        new Cities(	citiname:	'Intan Jaya '	).save()
//        new Cities(	citiname:	'Jayapura '	).save()
//        new Cities(	citiname:	'Jayawijaya '	).save()
//        new Cities(	citiname:	'Jember '	).save()
//        new Cities(	citiname:	'Jembrana '	).save()
//        new Cities(	citiname:	'Jeneponto '	).save()
//        new Cities(	citiname:	'Jepara '	).save()
//        new Cities(	citiname:	'Jombang '	).save()
//        new Cities(	citiname:	'Kaimana '	).save()
//        new Cities(	citiname:	'Kampar '	).save()
//        new Cities(	citiname:	'Kapuas '	).save()
//        new Cities(	citiname:	'Kapuas Hulu '	).save()
//        new Cities(	citiname:	'Karanganyar '	).save()
//        new Cities(	citiname:	'Karangasem '	).save()
//        new Cities(	citiname:	'Karawang '	).save()
//        new Cities(	citiname:	'Karimun '	).save()
//        new Cities(	citiname:	'Karo '	).save()
//        new Cities(	citiname:	'Katingan '	).save()
//        new Cities(	citiname:	'Kaur '	).save()
//        new Cities(	citiname:	'Kayong Utara '	).save()
//        new Cities(	citiname:	'Kebumen '	).save()
//        new Cities(	citiname:	'Kediri '	).save()
//        new Cities(	citiname:	'Keerom '	).save()
//        new Cities(	citiname:	'Kendal '	).save()
//        new Cities(	citiname:	'Kepahiang '	).save()
//        new Cities(	citiname:	'Kepulauan Anambas '	).save()
//        new Cities(	citiname:	'Kepulauan Aru '	).save()
//        new Cities(	citiname:	'Kepulauan Mentawai '	).save()
//        new Cities(	citiname:	'Kepulauan Meranti '	).save()
//        new Cities(	citiname:	'Kepulauan Sangihe '	).save()
//        new Cities(	citiname:	'Kepulauan Selayar '	).save()
//        new Cities(	citiname:	'Kepulauan Siau Tagulandang Biaro '	).save()
//        new Cities(	citiname:	'Kepulauan Sula '	).save()
//        new Cities(	citiname:	'Kepulauan Talaud '	).save()
//        new Cities(	citiname:	'Kepulauan Yapen '	).save()
//        new Cities(	citiname:	'Kerinci '	).save()
//        new Cities(	citiname:	'Ketapang '	).save()
//        new Cities(	citiname:	'Klaten '	).save()
//        new Cities(	citiname:	'Klungkung '	).save()
//        new Cities(	citiname:	'Kolaka '	).save()
//        new Cities(	citiname:	'Kolaka Utara '	).save()
//        new Cities(	citiname:	'Konawe '	).save()
//        new Cities(	citiname:	'Konawe Selatan '	).save()
//        new Cities(	citiname:	'Konawe Utara '	).save()
//        new Cities(	citiname:	'Kotabaru '	).save()
//        new Cities(	citiname:	'Kotawaringin Barat '	).save()
//        new Cities(	citiname:	'Kotawaringin Timur '	).save()
//        new Cities(	citiname:	'Kuantan Singingi '	).save()
//        new Cities(	citiname:	'Kubu Raya '	).save()
//        new Cities(	citiname:	'Kudus '	).save()
//        new Cities(	citiname:	'Kulon Progo '	).save()
//        new Cities(	citiname:	'Kuningan '	).save()
//        new Cities(	citiname:	'Kupang '	).save()
//        new Cities(	citiname:	'Kutai Barat '	).save()
//        new Cities(	citiname:	'Kutai Kartanegara '	).save()
//        new Cities(	citiname:	'Kutai Timur '	).save()
//        new Cities(	citiname:	'Labuhanbatu '	).save()
//        new Cities(	citiname:	'Labuhanbatu Selatan '	).save()
//        new Cities(	citiname:	'Labuhanbatu Utara '	).save()
//        new Cities(	citiname:	'Lahat '	).save()
//        new Cities(	citiname:	'Lamandau '	).save()
//        new Cities(	citiname:	'Lamongan '	).save()
//        new Cities(	citiname:	'Lampung Barat '	).save()
//        new Cities(	citiname:	'Lampung Selatan '	).save()
//        new Cities(	citiname:	'Lampung Tengah '	).save()
//        new Cities(	citiname:	'Lampung Timur '	).save()
//        new Cities(	citiname:	'Lampung Utara '	).save()
//        new Cities(	citiname:	'Landak '	).save()
//        new Cities(	citiname:	'Langkat '	).save()
//        new Cities(	citiname:	'Lanny Jaya '	).save()
//        new Cities(	citiname:	'Lebak '	).save()
//        new Cities(	citiname:	'Lebong '	).save()
//        new Cities(	citiname:	'Lembata '	).save()
//        new Cities(	citiname:	'Lima Puluh '	).save()
//        new Cities(	citiname:	'Lingga '	).save()
//        new Cities(	citiname:	'Lombok Barat '	).save()
//        new Cities(	citiname:	'Lombok Tengah '	).save()
//        new Cities(	citiname:	'Lombok Timur '	).save()
//        new Cities(	citiname:	'Lombok Utara '	).save()
//        new Cities(	citiname:	'Lumajang '	).save()
//        new Cities(	citiname:	'Luwu '	).save()
//        new Cities(	citiname:	'Luwu Timur '	).save()
//        new Cities(	citiname:	'Luwu Utara '	).save()
//        new Cities(	citiname:	'Madiun '	).save()
//        new Cities(	citiname:	'Magelang '	).save()
//        new Cities(	citiname:	'Magetan '	).save()
//        new Cities(	citiname:	'Majalengka '	).save()
//        new Cities(	citiname:	'Majene '	).save()
//        new Cities(	citiname:	'Malang '	).save()
//        new Cities(	citiname:	'Malinau '	).save()
//        new Cities(	citiname:	'Maluku Barat Daya '	).save()
//        new Cities(	citiname:	'Maluku Tengah '	).save()
//        new Cities(	citiname:	'Maluku Tenggara '	).save()
//        new Cities(	citiname:	'Maluku Tenggara Barat '	).save()
//        new Cities(	citiname:	'Mamasa '	).save()
//        new Cities(	citiname:	'Mamberamo Raya '	).save()
//        new Cities(	citiname:	'Mamberamo Tengah '	).save()
//        new Cities(	citiname:	'Mamuju '	).save()
//        new Cities(	citiname:	'Mamuju Utara '	).save()
//        new Cities(	citiname:	'Mandailing Natal '	).save()
//        new Cities(	citiname:	'Manggarai '	).save()
//        new Cities(	citiname:	'Manggarai Barat '	).save()
//        new Cities(	citiname:	'Manggarai Timur '	).save()
//        new Cities(	citiname:	'Manokwari '	).save()
//        new Cities(	citiname:	'Mappi '	).save()
//        new Cities(	citiname:	'Maros '	).save()
//        new Cities(	citiname:	'Maybrat '	).save()
//        new Cities(	citiname:	'Melawi '	).save()
//        new Cities(	citiname:	'Merangin '	).save()
//        new Cities(	citiname:	'Merauke '	).save()
//        new Cities(	citiname:	'Mesuji '	).save()
//        new Cities(	citiname:	'Mimika '	).save()
//        new Cities(	citiname:	'Minahasa '	).save()
//        new Cities(	citiname:	'Minahasa Selatan '	).save()
//        new Cities(	citiname:	'Minahasa Tenggara '	).save()
//        new Cities(	citiname:	'Minahasa Utara '	).save()
//        new Cities(	citiname:	'Mojokerto '	).save()
//        new Cities(	citiname:	'Morowali '	).save()
//        new Cities(	citiname:	'Muara Enim '	).save()
//        new Cities(	citiname:	'Muaro Jambi '	).save()
//        new Cities(	citiname:	'Mukomuko '	).save()
//        new Cities(	citiname:	'Muna '	).save()
//        new Cities(	citiname:	'Murung Raya '	).save()
//        new Cities(	citiname:	'Musi Banyuasin '	).save()
//        new Cities(	citiname:	'Musi Rawas '	).save()
//        new Cities(	citiname:	'Nabire '	).save()
//        new Cities(	citiname:	'Nagan Raya '	).save()
//        new Cities(	citiname:	'Nagekeo '	).save()
//        new Cities(	citiname:	'Natuna '	).save()
//        new Cities(	citiname:	'Nduga '	).save()
//        new Cities(	citiname:	'Ngada '	).save()
//        new Cities(	citiname:	'Nganjuk '	).save()
//        new Cities(	citiname:	'Ngawi '	).save()
//        new Cities(	citiname:	'Nias '	).save()
//        new Cities(	citiname:	'Nias Barat '	).save()
//        new Cities(	citiname:	'Nias Selatan '	).save()
//        new Cities(	citiname:	'Nias Utara '	).save()
//        new Cities(	citiname:	'Nunukan '	).save()
//        new Cities(	citiname:	'Ogan Ilir '	).save()
//        new Cities(	citiname:	'Ogan Komering Ilir '	).save()
//        new Cities(	citiname:	'Ogan Komering Ulu '	).save()
//        new Cities(	citiname:	'Ogan Komering Ulu Selatan '	).save()
//        new Cities(	citiname:	'Ogan Komering Ulu Timur '	).save()
//        new Cities(	citiname:	'Pacitan '	).save()
//        new Cities(	citiname:	'Padang Lawas '	).save()
//        new Cities(	citiname:	'Padang Lawas Utara '	).save()
//        new Cities(	citiname:	'Padang Pariaman '	).save()
//        new Cities(	citiname:	'Pakpak Bharat '	).save()
//        new Cities(	citiname:	'Pamekasan '	).save()
//        new Cities(	citiname:	'Pandeglang '	).save()
//        new Cities(	citiname:	'Pangkajene dan Kepulauan '	).save()
//        new Cities(	citiname:	'Paniai '	).save()
//        new Cities(	citiname:	'Parigi Moutong '	).save()
//        new Cities(	citiname:	'Pasaman '	).save()
//        new Cities(	citiname:	'Pasaman Barat '	).save()
//        new Cities(	citiname:	'Paser '	).save()
//        new Cities(	citiname:	'Pasuruan '	).save()
//        new Cities(	citiname:	'Pati '	).save()
//        new Cities(	citiname:	'Pegunungan Bintang '	).save()
//        new Cities(	citiname:	'Pekalongan '	).save()
//        new Cities(	citiname:	'Pelalawan '	).save()
//        new Cities(	citiname:	'Pemalang '	).save()
//        new Cities(	citiname:	'Penajam Paser Utara '	).save()
//        new Cities(	citiname:	'Pesawaran '	).save()
//        new Cities(	citiname:	'Pesisir Selatan '	).save()
//        new Cities(	citiname:	'Pidie '	).save()
//        new Cities(	citiname:	'Pidie Jaya '	).save()
//        new Cities(	citiname:	'Pinrang '	).save()
//        new Cities(	citiname:	'Pohuwato '	).save()
//        new Cities(	citiname:	'Polewali Mandar '	).save()
//        new Cities(	citiname:	'Ponorogo '	).save()
//        new Cities(	citiname:	'Pontianak '	).save()
//        new Cities(	citiname:	'Poso '	).save()
//        new Cities(	citiname:	'Pringsewu '	).save()
//        new Cities(	citiname:	'Probolinggo '	).save()
//        new Cities(	citiname:	'Pulang Pisau '	).save()
//        new Cities(	citiname:	'Pulau Morotai '	).save()
//        new Cities(	citiname:	'Puncak '	).save()
//        new Cities(	citiname:	'Puncak Jaya '	).save()
//        new Cities(	citiname:	'Purbalingga '	).save()
//        new Cities(	citiname:	'Purwakarta '	).save()
//        new Cities(	citiname:	'Purworejo '	).save()
//        new Cities(	citiname:	'Raja Ampat '	).save()
//        new Cities(	citiname:	'Rejang Lebong '	).save()
//        new Cities(	citiname:	'Rembang '	).save()
//        new Cities(	citiname:	'Rokan Hilir '	).save()
//        new Cities(	citiname:	'Rokan Hulu '	).save()
//        new Cities(	citiname:	'Rote Ndao '	).save()
//        new Cities(	citiname:	'Sabu Raijua '	).save()
//        new Cities(	citiname:	'Sambas '	).save()
//        new Cities(	citiname:	'Samosir '	).save()
//        new Cities(	citiname:	'Sampang '	).save()
//        new Cities(	citiname:	'Sanggau '	).save()
//        new Cities(	citiname:	'Sarmi '	).save()
//        new Cities(	citiname:	'Sarolangun '	).save()
//        new Cities(	citiname:	'Sekadau '	).save()
//        new Cities(	citiname:	'Seluma '	).save()
//        new Cities(	citiname:	'Semarang '	).save()
//        new Cities(	citiname:	'Seram Bagian Barat '	).save()
//        new Cities(	citiname:	'Seram Bagian Timur '	).save()
//        new Cities(	citiname:	'Serang '	).save()
//        new Cities(	citiname:	'Serdang Bedagai '	).save()
//        new Cities(	citiname:	'Seruyan '	).save()
//        new Cities(	citiname:	'Siak '	).save()
//        new Cities(	citiname:	'Sidenreng Rappang '	).save()
//        new Cities(	citiname:	'Sidoarjo '	).save()
//        new Cities(	citiname:	'Sigi '	).save()
//        new Cities(	citiname:	'Sijunjung '	).save()
//        new Cities(	citiname:	'Sikka '	).save()
//        new Cities(	citiname:	'Simalungun '	).save()
//        new Cities(	citiname:	'Simeulue '	).save()
//        new Cities(	citiname:	'Sinjai '	).save()
//        new Cities(	citiname:	'Sintang '	).save()
//        new Cities(	citiname:	'Situbondo '	).save()
//        new Cities(	citiname:	'Sleman '	).save()
//        new Cities(	citiname:	'Solok '	).save()
//        new Cities(	citiname:	'Solok Selatan '	).save()
//        new Cities(	citiname:	'Soppeng '	).save()
//        new Cities(	citiname:	'Sorong '	).save()
//        new Cities(	citiname:	'Sorong Selatan '	).save()
//        new Cities(	citiname:	'Sragen '	).save()
//        new Cities(	citiname:	'Subang '	).save()
//        new Cities(	citiname:	'Sukabumi '	).save()
//        new Cities(	citiname:	'Sukamara '	).save()
//        new Cities(	citiname:	'Sukoharjo '	).save()
//        new Cities(	citiname:	'Sumba Barat '	).save()
//        new Cities(	citiname:	'Sumba Barat Daya '	).save()
//        new Cities(	citiname:	'Sumba Tengah '	).save()
//        new Cities(	citiname:	'Sumba Timur '	).save()
//        new Cities(	citiname:	'Sumbawa '	).save()
//        new Cities(	citiname:	'Sumbawa Barat '	).save()
//        new Cities(	citiname:	'Sumedang '	).save()
//        new Cities(	citiname:	'Sumenep '	).save()
//        new Cities(	citiname:	'Supiori '	).save()
//        new Cities(	citiname:	'Tabalong '	).save()
//        new Cities(	citiname:	'Tabanan '	).save()
//        new Cities(	citiname:	'Takalar '	).save()
//        new Cities(	citiname:	'Tambrauw '	).save()
//        new Cities(	citiname:	'Tana Tidung '	).save()
//        new Cities(	citiname:	'Tana Toraja '	).save()
//        new Cities(	citiname:	'Tanah Bumbu '	).save()
//        new Cities(	citiname:	'Tanah Datar '	).save()
//        new Cities(	citiname:	'Tanah Laut '	).save()
//        new Cities(	citiname:	'Tangerang '	).save()
//        new Cities(	citiname:	'Tanggamus '	).save()
//        new Cities(	citiname:	'Tanjung Jabung Barat '	).save()
//        new Cities(	citiname:	'Tanjung Jabung Timur '	).save()
//        new Cities(	citiname:	'Tapanuli Selatan '	).save()
//        new Cities(	citiname:	'Tapanuli Tengah '	).save()
//        new Cities(	citiname:	'Tapanuli Utara '	).save()
//        new Cities(	citiname:	'Tapin '	).save()
//        new Cities(	citiname:	'Tasikmalaya '	).save()
//        new Cities(	citiname:	'Tebo '	).save()
//        new Cities(	citiname:	'Tegal '	).save()
//        new Cities(	citiname:	'Teluk Bintuni '	).save()
//        new Cities(	citiname:	'Teluk Wondama '	).save()
//        new Cities(	citiname:	'Temanggung '	).save()
//        new Cities(	citiname:	'Timor Tengah Selatan '	).save()
//        new Cities(	citiname:	'Timor Tengah Utara '	).save()
//        new Cities(	citiname:	'Toba Samosir '	).save()
//        new Cities(	citiname:	'Tojo Una-Una '	).save()
//        new Cities(	citiname:	'Tolikara '	).save()
//        new Cities(	citiname:	'Toli-Toli '	).save()
//        new Cities(	citiname:	'Toraja Utara '	).save()
//        new Cities(	citiname:	'Trenggalek '	).save()
//        new Cities(	citiname:	'Tuban '	).save()
//        new Cities(	citiname:	'Tulang Bawang '	).save()
//        new Cities(	citiname:	'Tulang Bawang Barat '	).save()
//        new Cities(	citiname:	'Tulungagung '	).save()
//        new Cities(	citiname:	'Wajo '	).save()
//        new Cities(	citiname:	'Wakatobi '	).save()
//        new Cities(	citiname:	'Waropen '	).save()
//        new Cities(	citiname:	'Way Kanan '	).save()
//        new Cities(	citiname:	'Wonogiri '	).save()
//        new Cities(	citiname:	'Wonosobo '	).save()
//        new Cities(	citiname:	'Yahukimo '	).save()
//        new Cities(	citiname:	'Yalimo '	).save()
//        new Cities(	citiname:	'Jakarta'	).save()
//        new Cities(	citiname:	'Ambon '	).save()
//        new Cities(	citiname:	'Balikpapan '	).save()
//        new Cities(	citiname:	'Banda Aceh '	).save()
//        new Cities(	citiname:	'Bandar Lampung '	).save()
//        new Cities(	citiname:	'Bandung '	).save()
//        new Cities(	citiname:	'Banjar '	).save()
//        new Cities(	citiname:	'Banjarbaru '	).save()
//        new Cities(	citiname:	'Banjarmasin '	).save()
//        new Cities(	citiname:	'Batam '	).save()
//        new Cities(	citiname:	'Batu[8] '	).save()
//        new Cities(	citiname:	'Bau-Bau '	).save()
//        new Cities(	citiname:	'Bekasi '	).save()
//        new Cities(	citiname:	'Bengkulu '	).save()
//        new Cities(	citiname:	'Bima '	).save()
//        new Cities(	citiname:	'Binjai '	).save()
//        new Cities(	citiname:	'Bitung '	).save()
//        new Cities(	citiname:	'Blitar '	).save()
//        new Cities(	citiname:	'Bogor '	).save()
//        new Cities(	citiname:	'Bontang '	).save()
//        new Cities(	citiname:	'Bukittinggi '	).save()
//        new Cities(	citiname:	'Cilegon '	).save()
//        new Cities(	citiname:	'Cimahi '	).save()
//        new Cities(	citiname:	'Cirebon '	).save()
//        new Cities(	citiname:	'Denpasar '	).save()
//        new Cities(	citiname:	'Depok '	).save()
//        new Cities(	citiname:	'Dumai '	).save()
//        new Cities(	citiname:	'Gorontalo '	).save()
//        new Cities(	citiname:	'Gunungsitoli '	).save()
//        new Cities(	citiname:	'Jambi '	).save()
//        new Cities(	citiname:	'Jayapura '	).save()
//        new Cities(	citiname:	'Kediri '	).save()
//        new Cities(	citiname:	'Kendari '	).save()
//        new Cities(	citiname:	'Kotamobagu '	).save()
//        new Cities(	citiname:	'Kupang '	).save()
//        new Cities(	citiname:	'Langsa '	).save()
//        new Cities(	citiname:	'Lhokseumawe '	).save()
//        new Cities(	citiname:	'Lubuklinggau '	).save()
//        new Cities(	citiname:	'Madiun '	).save()
//        new Cities(	citiname:	'Magelang '	).save()
//        new Cities(	citiname:	'Makassar '	).save()
//        new Cities(	citiname:	'Malang '	).save()
//        new Cities(	citiname:	'Manado '	).save()
//        new Cities(	citiname:	'Mataram '	).save()
//        new Cities(	citiname:	'Medan '	).save()
//        new Cities(	citiname:	'Metro '	).save()
//        new Cities(	citiname:	'Mojokerto '	).save()
//        new Cities(	citiname:	'Padang '	).save()
//        new Cities(	citiname:	'Padangpanjang '	).save()
//        new Cities(	citiname:	'Padangsidempuan '	).save()
//        new Cities(	citiname:	'Pagar Alam '	).save()
//        new Cities(	citiname:	'Palangka Raya '	).save()
//        new Cities(	citiname:	'Palembang '	).save()
//        new Cities(	citiname:	'Palopo '	).save()
//        new Cities(	citiname:	'Palu '	).save()
//        new Cities(	citiname:	'Pangkal Pinang '	).save()
//        new Cities(	citiname:	'Parepare '	).save()
//        new Cities(	citiname:	'Pariaman '	).save()
//        new Cities(	citiname:	'Pasuruan '	).save()
//        new Cities(	citiname:	'Payakumbuh '	).save()
//        new Cities(	citiname:	'Pekalongan '	).save()
//        new Cities(	citiname:	'Pekanbaru '	).save()
//        new Cities(	citiname:	'Pematangsiantar '	).save()
//        new Cities(	citiname:	'Pontianak '	).save()
//        new Cities(	citiname:	'Prabumulih '	).save()
//        new Cities(	citiname:	'Probolinggo '	).save()
//        new Cities(	citiname:	'Sabang '	).save()
//        new Cities(	citiname:	'Salatiga '	).save()
//        new Cities(	citiname:	'Samarinda '	).save()
//        new Cities(	citiname:	'Sawahlunto '	).save()
//        new Cities(	citiname:	'Semarang '	).save()
//        new Cities(	citiname:	'Serang '	).save()
//        new Cities(	citiname:	'Sibolga '	).save()
//        new Cities(	citiname:	'Singkawang '	).save()
//        new Cities(	citiname:	'Solok '	).save()
//        new Cities(	citiname:	'Sorong '	).save()
//        new Cities(	citiname:	'Subulussalam '	).save()
//        new Cities(	citiname:	'Sukabumi '	).save()
//        new Cities(	citiname:	'Sungai Penuh '	).save()
//        new Cities(	citiname:	'Surabaya '	).save()
//        new Cities(	citiname:	'Surakarta '	).save()
//        new Cities(	citiname:	'Tangerang '	).save()
//        new Cities(	citiname:	'Tangerang Selatan '	).save()
//        new Cities(	citiname:	'Tanjung Pinang '	).save()
//        new Cities(	citiname:	'Tanjungbalai '	).save()
//        new Cities(	citiname:	'Tarakan '	).save()
//        new Cities(	citiname:	'Tasikmalaya '	).save()
//        new Cities(	citiname:	'Tebing Tinggi '	).save()
//        new Cities(	citiname:	'Tegal '	).save()
//        new Cities(	citiname:	'Ternate '	).save()
//        new Cities(	citiname:	'Tidore Kepulauan '	).save()
//        new Cities(	citiname:	'Tomohon '	).save()
//        new Cities(	citiname:	'Tual '	).save()
//        new Cities(	citiname:	'Yogyakarta '	).save()
//new Hospspecialist(	specialistname:	'Dokter Umum ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Anak ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Andrologi ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Anestesiologi dan Reanimasi ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Bedah ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Bedah Anak ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Bedah Mulut dan Maksilofasial ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Bedah Orthopaedi dan Traumatologi ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Bedah Plastik ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Bedah Toraks Kardiovaskuler ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis BedahSaraf ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Farmakologi Klinik ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Geriatri ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Jantung dan Pembuluh Darah ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Kedaruratan Medik ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Kedokteran Fisik dan Rehabilitasi ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Kedokteran Forensik ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Kedokteran Gigi Anak (dokter gigi) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Kedokteran Jiwa atau Psikiatri ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Kedokteran Nuklir ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Kedokteran Okupasi (kerja) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Kedokteran Olahraga ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Konservasi Gigi (dokter gigi) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Mata ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Mikrobiologi Klinik ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Obstetri & Ginekologi (kebidanan dan kandungan) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Onkologi Radiasi ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Ortodonsia (perawatan maloklusi) (dokter gigi) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Paru (Pulmonologi) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Patologi Anatomi ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Patologi Klinik ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Penyakit Dalam ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Penyakit Kulit dan Kelamin ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Penyakit Mulut (dokter gigi) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Periodonsia (jaringan gusi dan penyangga gigi) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Prostodonsia (restorasi rongga mulut) (dokter gigi) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Radiologi ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Radiologi Kedokteran Gigi (dokter gigi) ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Rehabilitasi Medik ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Saraf ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Telinga Hidung Tenggorok ',	).save()
//new Hospspecialist(	specialistname:	'Spesialis Urologi ',	).save()

    }
    def destroy = {
    }
}
